### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by kxmbrian** [moexmen/coursemology-sls#6]
- Critical feature: allow teachers to duplicate existing material to SLS courses.

### Decision Points
- [ ] [Pending] Do we only allow duplication of assessments?
    - If yes, need to customize the duplication component.

**Comment by weiqingtoh** [comment]
We will need to support duplication of assessments because teachers will need to duplicate assessments from one subject group to another once the year has passed. 

There are a few ways of handling this, one is to only allow 'cherry-pick' duplication of enabled components (and disable all non-assessment components), while another is to have a customised duplication component.

**Comment by kxmbrian** [comment]
Since courses are only created via SLS, the course duplication mode will have to be disabled.

A possible mechanism for teachers to share materials without the need of a public interface is as follows:
1. Allow teachers to invite existing SLS users to join their course (by providing their `sls_id`s) as a 'read-only phantom'.
    - This course membership is managed by Coursemology and SLS is not aware of it.
    - The 'read-only phantom' role will allow teachers to preview duplicable items and duplicate them, but not edit them.
2. Allow teachers to navigate to other courses they are members of once they have entered the Coursemology app from any SLS course.
3. Once they are in the source course, they can duplicate items via the usual flow.

As suggested by @weiqingtoh, instead of having to navigate to the source course to make the duplication, we can also have an interface that allows the user to 'pull' items from other courses from within the destination course.
